### ISSUE TITLE
Flute luts directory

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenPhySyn#2]
Hello,

I would like to report a small issue or inconvenience. I got this error after running the binary `Psn`. 

```
[error] Flute initialization failed
```
I think that's due to `initializeFlute` search for luts in `../external/flute/etc`.  https://github.com/The-OpenROAD-Project/OpenPhySyn/blob/b6267b7fda0e1772e738ae17c250d4e0fc2e3fc4/src/Psn/Psn.cpp#L92

Perhaps it can search the current working directory as well.

**Comment by ahmed-agiza** [comment]
We will embed the LUT files in the compiled files in future releases to avoid this external dependency, for now, I added several lookup attempts to address this inconvenience in addition to including the LUT files in the installation target. fb76b5e
Also, there are some changes for read/write command names, you may refer to the CHANGELOG.
