### ISSUE TITLE
Crash with buffer_fanout

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenPhySyn#3]
Hello,

I was trying out buffer_fanout. After executing it using `optimize_fanout -buffer_cell <cell> -max_fanout <fanout>`. It outputs `[2019-12-16 08:44:26.345] [info] High fanout nets [4390]: 
`, followed by a crash (segmentation violation). This is the sequence of commands that I used:

```
import_lef
import_def
import_lib
link_design
set_wire_rc
optimize_fanout
```
Is there anything missing?

**Comment by ahmed-agiza** [comment]
Can you provide the test files if they can be published (or in private if you prefer)? Or at least the core dump and the tool logs? It is a bit hard to replicate with only the sequence of command (given that there is a similar working sequence here: https://github.com/The-OpenROAD-Project/OpenPhySyn/blob/master/tests/tcl/buffer_transform.tcl)

**Comment by kareefardi** [comment]
Closed for now. Until I have time to investigate further. Thank you
